stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo "PYTHON TEST SHOULD RUN HERE"


buildreactapp:
  image: node:12.13.1
  stage: build
  script:
    - yarn install
    - yarn run build --prod
    - tar -cvf webapp.tar build appspec.yml scripts
    - mkdir -p dpl_cd_upload
    - mv webapp.tar dpl_cd_upload/webapp.tar
  rules:
    changes:
        - .gitlab-ci.yml
        - docker-compose.yml
        - web-app/*
  artifacts:
    paths:
         - dpl_cd_upload/

build:
  stage: build
  script:
    - tar -cvf serverapp.tar sidon-app docker-compose.yml web-app config scripts appspec.yml
    - mkdir -p dpl_cd_upload
    - mv serverapp.tar dpl_cd_upload/serverapp.tar
  artifacts:
    paths:
         - dpl_cd_upload/



deploy:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=s3 --bucket=sidonrevisions --upload_dir=latest --region=eu-west-3 --bundle_type=tar --local_dir=dpl_cd_upload --skip_cleanup=true
    - dpl --provider=codedeploy --application=SidonApp --revision_type=s3 --bucket=sidonrevisions --key=latest/serverapp.tar --deployment-group-name=SidonApp --wait_until_deployed --region=eu-west-3 --file_exists_behavior=overwrite --description='GitLab Devops'
  environment:
    name: production
    url: http://15.188.48.8
  only:
    - master
