stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo "PYTHON TEST SHOULD RUN HERE"


build:webapp:
  image: node:12.13.1
  stage: build
  script:
    - cd web-app
    - yarn install
    - yarn run build
    - tar -cvf webapp.tar build  scripts appspec.yml
    - mkdir -p ../webapp_upload
    - mv webapp.tar ../webapp_upload/webapp.tar
  rules:
    - changes:
        - .gitlab-ci.yml
        - docker-compose.yml
        - web-app/*
  artifacts:
    paths:
         - webapp_upload/

deploy:webapp:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=s3 --bucket=sidonrevisions --upload_dir=latest --region=eu-west-3 --bundle_type=tar --local_dir=webapp_upload --skip_cleanup=true
    - dpl --provider=codedeploy --application=SidonApp --revision_type=s3 --bucket=sidonrevisions --key=latest/webapp.tar --deployment-group-name=WebApp --wait_until_deployed --region=eu-west-3 --file_exists_behavior=overwrite --description='GitLab Devops'
  environment:
    name: production
    url: http://15.188.48.8
  rules:
    - changes:
        - .gitlab-ci.yml
        - docker-compose.yml
        - web-app/*
  needs:
    - job: build:webapp
      artifacts: true
  only:
    - master

build:serverapp:
  stage: build
  script:
    - tar -cvf serverapp.tar sidon-app docker-compose.yml web-app config scripts appspec.yml
    - mkdir -p dpl_cd_upload
    - mv serverapp.tar dpl_cd_upload/serverapp.tar
  rules:
    - changes:
        - .gitlab-ci.yml
        - docker-compose.yml
        - sidon-app/*
        - config
        - scripts
        - appspec.yml
  artifacts:
    paths:
         - dpl_cd_upload/

deploy:serverapp:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=s3 --bucket=sidonrevisions --upload_dir=latest --region=eu-west-3 --bundle_type=tar --local_dir=dpl_cd_upload --skip_cleanup=true
    - dpl --provider=codedeploy --application=SidonApp --revision_type=s3 --bucket=sidonrevisions --key=latest/serverapp.tar --deployment-group-name=ServerApp --wait_until_deployed --region=eu-west-3 --file_exists_behavior=overwrite --description='GitLab Devops'
  environment:
    name: production
    url: http://15.188.48.8
  needs:
    - job: build:serverapp
      artifacts: true
  only:
    - master
