version: 0.0
os: linux
files:
  - source: ./
    destination: /opt/app
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
  ApplicationStart:
    - location: scripts/restart-server.sh
      timeout: 3600
