version: '3'

services:

  sidon-app:
    build:
      context: ./sidon-app
      dockerfile: Dockerfile.dev
    volumes:
      - ./sidon-app:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/static  # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/media  # <-- bind the media volume
    networks:
      - nginx_network
      - database_network

  nginx:
    image: nginx:1.17.4
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./web-app/build:/opt/webapp/html
      - static_volume:/opt/services/djangoapp/static
      - media_volume:/opt/services/djangoapp/media
      - document_root:/opt/services/webapp/root
    depends_on:
      - sidon-app
    networks:
      - nginx_network

  database:
    image: postgres:11
    env_file:
      - config/database/db_env
    networks:
      - database_network
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mlengine:
    build:  ml-engine
    volumes:
      - ./ml-engine/app:/opt/services/engine
    ports:
      - 5000:5000

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  document_root:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume
